Deflake WebViewZoomTest (multiple callbacks per zoomBy)
Multiple calls to zoomBy in a short space of time can cause us to
receive multiple callbacks from WebView on the subsequent calls within
floating point error range and this will lead to the following kind of
failure:

  AssertionError: Expected new scale < current scale when zooming out
      Expected: a value less than <4.9F>
      but: <4.9000006F> was greater than <4.9F>

The next event after this will be the one we actually want and the test
will pass as expected if we wait for it.

Change-Id: I960d609ac95ede273faaa64a454e98f3d7eee9f2
Test: atest WebViewZoomTest
Fix: 165515726

Former-commit-id: 49787ca45c00596d2c3f4220ee8faf0b60349080