DisplayTests: scale by 0.9 for resolution override
DisplayTests.testForceDisplayMetrics() takes the size reported by
`wm size`, multiplies it by 1.5 in both dimensions, and checks that
a request for that display size is reflected in the `wm size` output.

This does not play well with the config_maxUiWidth framework resource,
which restricts any such requests.

Example 1: 1080x2520 device, config_maxUiWidth at 1096.
           FAIL: expected:<1620x3780> but was:<1096x2557>
Example 2: 1096x2560 device, config_maxUiWidth at 1096.
           FAIL: expected:<1644x3840> but was:<null>

The null value comes from the fact that `wm size` does not output any
"Override size" line when it is identical to the "Physical size" value
(and 1644x3840 restricted to 1096 clearly ends up at the original size).

Scaling by 0.9 instead of 1.5 avoids this problem.

Bug: 205072351
Test: cts-tradefed run cts -m CtsWindowManagerDeviceTestCases \
      -t 'android.server.wm.DisplayTests#testForceDisplayMetrics'
Change-Id: Idb88295b05fd7aef96623b91c3e49f39387f7e82
(cherry picked from commit 3fcbaf765876d1d26c0b9706abbf54461767846f [formerly cd6b0aa34fa659b36b7d18dcec1b08e3479fda02])

Former-commit-id: c584d3d5f1bc1aa8a469c6d4416218eca9f7bb62