fix CtsDevicePolicyManagerTestCases with to failed case --com.android.cts.devicepolicy.MixedDeviceOwnerTest#testLockTaskAfterReboot_tryOpeningSettings --com.android.cts.devicepolicy.MixedDeviceOwnerTest#testLockTaskAfterRebootthere
test:run cts -m CtsDevicePolicyManagerTestCases -t com.android.cts.devicepolicy.MixedDeviceOwnerTest#testLockTaskAfterReboot

fail info：
java.lang.AssertionError: on-device tests failed:
com.android.cts.deviceandprofileowner.LockTaskHostDrivenTest#testLockTaskIsActiveAndCantBeInterrupted:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getClassName()' on a null object reference
	at com.android.cts.deviceandprofileowner.LockTaskHostDrivenTest.checkLockedActivityIsRunning(LockTaskHostDrivenTest.java:253)
	at com.android.cts.deviceandprofileowner.LockTaskHostDrivenTest.testLockTaskIsActiveAndCantBeInterrupted(LockTaskHostDrivenTest.java:115)

Modify：

After add [android:directBootAware="true"] for default home Activity, when mUiDevice.pressBack(),
 LockTaskUtilityActivityIfWhitelisted will finish, then topActivity is null;
So add a NullPointerException judgment


Bug:193216395

This bug was caused  [android:directBootAware="true"]  added for default home Activity

Change-Id: Ibc905b9c842467516ce78356c73bbc7eeee7f3d9

Former-commit-id: b5cfc14a725403812031de91e961d769194500ca