Copied LocationModeSetter to CtsDevicePolicyManagerTestCases.
It was causing NoClassDefFoundError in some devices, and
CtsDevicePolicyManagerTestCases was including
compatibility-host-util-axt just because of it.

Test: atest com.android.cts.devicepolicy.DeviceOwnerTest#testWifiConfigLockdown

Bug: 149827369
Fixes: 181682411

Change-Id: Ib90b80a52a2980f88d20e916136a5dd712b3d12a

Former-commit-id: 220f928f54c246bd567332ad3669e8687e1c175e