Signature tests: catch and log NoClassDefFoundError
Avoids failing the tests if a NoClassDefFoundError is detected when
attempting to retrieve a class or its constructors, methods or fields
using reflection. Instead log the failure and continue.

This should not make the tests any less rigorous or risk allowing
access to implementation details of the platform as if the test cannot
retrieve them using reflection then an app will be unable to do so
either.

Bug: 206650495
Test: m CtsSystemApiAnnotationTestCases
Merged-In: I94716a359aaa8c88429143130566ec4db13a7ad8
Change-Id: I94716a359aaa8c88429143130566ec4db13a7ad8
(cherry picked from commit 86131e5e4676eb76c8e7f7ccc24ab4a328c26c33 [formerly 4477f56cd99637be916c8a9f4d5257003cb5328d])

Former-commit-id: 793dd6a743146a6e4a725e613c7110b4d1c05bc4