SELinuxHostTest: Fix location of sepolicy-analyze
The location of the sepolicy-analyze binary has evidently changed from
/tmp/<more dirs>/sepolicy-analyze to
/tmp/<more dirs>/sepolicy-analyze/sepolicy-analyze. Update tests to
point to the new location.

Addresses a bunch of test failures such as:
junit.framework.AssertionFailedError: cannot execute binary file

Test: atest SELinuxHostTest
Fixes: 144051065
Change-Id: If9e12ddbe980d94738f41c250fa2148f4ff1366f

Former-commit-id: 8d8ec632c94d11936b697ea97b7518804bd28282