Add SHOW_INPUT_METHOD_PICKER broadcast test
The CL [1] introduced a protected-broadcast intent action for internal
use. This CL ensures that the protected-broadcast intent can't be
invoked by non-system user.

 [1]: Id36c8c34159bea8b72557b40bcf024d401f580b6

Bug: 63644555
Test: Passed CTS permission2 test.
    $ cts-tradefed run singleCommand cts-dev \
          -m CtsPermission2TestCases \
	  -t android.permission2.cts.ProtectedBroadcastsTest
Test: Confirmed the following command causes error.
    $ adb shell am broadcast \
          -a com.android.server.InputMethodManagerService.SHOW_INPUT_METHOD_PICKER
    java.lang.SecurityException: Permission Denial: not allowed to send
    broadcast com.android.server.InputMethodManagerService.SHOW_INPUT_METHOD_PICKER
    from pid=xxxx, uid=xxxx
Change-Id: Ib58d2931cc8db3b88eab64352ba445be67eaec68