Fixed testAlwaysOnVpnPackageXXX tests for headless system user mode.
They need to run on device owner user.

NOTE: AlwaysOnVpnUnsupportedTest#testClearAlwaysOnVpn fails when running
together with the others:

junit.framework.AssertionFailedError: Failed to clear always-on package

But it pass standalone.

Test: atest com.android.cts.devicepolicy.MixedDeviceOwnerTest#testAlwaysOnVpn,testAlwaysOnVpnLockDown,testAlwaysOnVpnAcrossReboot,testAlwaysOnVpnPackageUninstalled,testAlwaysOnVpnUnsupportedPackage,testAlwaysOnVpnUnsupportedPackageReplaced # on automotive and phone

Fixes: 189266627
Bug: 192395248
Bug: 193814739

Change-Id: I8780822a264ddd529fb2c281a6596b0fc832bf61

Former-commit-id: a2ff6d4e702f827887cdccba6406043fa2cdb255