Allow MethodHandle.invoke/invokeExact to be used in tests
If LOCAL_MIN_SDK_VERSION is set to less than 26 then attempting to use
MethodHandle.invoke/invokeExact results in a build error:

Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)

That is blocking refactoring of this code.

Also, this ensures that if the minSdkVersion attribute is set in an
AndroidManifest.xml then the LOCAL_MIN_SDK_VERSION is set to the same
value in the corresponding build module. See change
I3883c56394bf9b2b47e97518b57af2d1cb79cb79 for more information.

Test: atest -p cts/tests/signature
Change-Id: I4d86445ed6d4e89a91c0ca1e0159e49b40808c17

Former-commit-id: e85a902aa4c5c7323152550307a4a28b461ea298